In [1]:
import numpy as np
numpy_test=np.array([1,2,3])
numpy_test

array([1, 2, 3])

In [2]:
list1=[1,2,3,4]
numpy_test2=np.array([list1])
numpy_test2


array([[1, 2, 3, 4]])

In [4]:
numpy_1d=np.array([4,5,6,7])
numpy_1d.ndim

1

In [7]:
numpy_2d=np.array([[1,2,3,4],[3,4,5,6]])
numpy_2d.ndim

2

In [8]:
numpy_3d=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]])
numpy_3d.ndim

2

In [10]:
n1=np.array()
n1

TypeError: array() missing required argument 'object' (pos 0)

In [13]:
n1=np.zeros(9)
n1

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
n2=np.ones(5)
n2

array([1., 1., 1., 1., 1.])

In [18]:
n3=np.array(["alia",3,"ayeza",0.7,1,0])
n3

array(['alia', '3', 'ayeza', '0.7', '1', '0'], dtype='<U32')

In [23]:
n4=np.array(["ali","arif","asim"])
n4

array(['ali', 'arif', 'asim'], dtype='<U4')

In [24]:
n5=np.arange(10)
n5


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
n5=np.arange(4,8)
n5

array([4, 5, 6, 7])

In [26]:
n5=np.arange(4,9)
n5

array([4, 5, 6, 7, 8])

In [31]:
n5=np.arange(4,17,3)
n5

array([ 4,  7, 10, 13, 16])

In [35]:
n6=np.linspace(3,21)
n6

array([ 3.        ,  3.36734694,  3.73469388,  4.10204082,  4.46938776,
        4.83673469,  5.20408163,  5.57142857,  5.93877551,  6.30612245,
        6.67346939,  7.04081633,  7.40816327,  7.7755102 ,  8.14285714,
        8.51020408,  8.87755102,  9.24489796,  9.6122449 ,  9.97959184,
       10.34693878, 10.71428571, 11.08163265, 11.44897959, 11.81632653,
       12.18367347, 12.55102041, 12.91836735, 13.28571429, 13.65306122,
       14.02040816, 14.3877551 , 14.75510204, 15.12244898, 15.48979592,
       15.85714286, 16.2244898 , 16.59183673, 16.95918367, 17.32653061,
       17.69387755, 18.06122449, 18.42857143, 18.79591837, 19.16326531,
       19.53061224, 19.89795918, 20.26530612, 20.63265306, 21.        ])

In [41]:
#third column shows no. we want to generate, as in this example 5 number array is generated
n6=np.linspace(2,16,5)
n6

array([ 2. ,  5.5,  9. , 12.5, 16. ])

In [48]:
n7=np.array([1])
n7.ndim

1

In [46]:
n7=np.array([[1]])
n7.ndim

2

In [47]:
n7=np.array([[[1]]])
n7.ndim

3

In [52]:
n8=np.array([[1,2,3,4],[4,5,6,8]])
n8

array([[1, 2, 3, 4],
       [4, 5, 6, 8]])

In [53]:
n9=np.array([[4,6,7,8],[8,7,5,4]])
n9

array([[4, 6, 7, 8],
       [8, 7, 5, 4]])

In [62]:
n9=np.concatenate((n8,n9))
n9

array([[1, 2, 3, 4],
       [4, 5, 6, 8],
       [4, 6, 7, 8],
       [8, 7, 5, 4]])

In [68]:
fake_data=np.random.rand(3)
fake_data

array([0.0137704 , 0.89872942, 0.71009228])

In [69]:
fake_data1=fake_data*3
fake_data1

array([0.0413112 , 2.69618827, 2.13027685])

In [70]:
fake_data+fake_data1

array([0.05508159, 3.59491769, 2.84036913])

In [74]:
fake_list=list(fake_data)
fake_list


[0.013770398540425277, 0.8987294235912218, 0.7100922821994369]

In [75]:
type(fake_list)

list

In [78]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [79]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])